<?php

const LANG_RIGHTS = [
    /* 00 */    'you must be an admin in the chat or have root right',
    /* 01 */    'right value must be 0 or 1',
    /* 02 */    'invalid right or chat',
    /* 03 */    'Right changed successfully',
    /* 04 */    'Chat administrator',
    /* 05 */    'No rights',
    /* 06 */    'Member rights:',
    /* 07 */    '<right> <0/1> <target> [chats/pm/every or current chat by default]',
    /* 08 */    'All rights',
    /* 09 */    'List of rights:',
    /* 10 */    'you must have right: %s',
    /* 11 */    'rights already registered: %s',
    /* 12 */    'Setting the right value for the member',
    /* 13 */    '<target>',
    /* 14 */    'Learn member rights',
    /* 15 */    'List with names and descriptions of available rights',
    /* 16 */    'Rights management',
    /* 17 */    'Adds rights system',
    /* 18 */    'rights',
    /* 19 */    'set',
    /* 20 */    'info',
    /* 21 */    'list',
];